import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import AppLayout from './component/AppLayout/AppLayout'
import Button from './component/Button'
import GitHub from './component/Icons/GitHub'
import {loginGitHub, onAuthStateChange} from './../firebase/client'
import {GithubAuthProvider } from "firebase/auth";
import {useState, useEffect} from 'react'

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    onAuthStateChange(user => setUser(user));
  });
  
  const handleClick = () => {
    loginGitHub()
            .then(res => {
              // This gives you a GitHub Access Token. You can use it to access the GitHub API.
              const credential = GithubAuthProvider.credentialFromResult(res);
              const token = credential.accessToken;
              // The signed-in user info.
              setUser(res.user);
              const user = res.user;
              console.log('res: ', res);
              console.log('user: ', user);
            })
            .catch((error) => {
              // Handle Errors here.
              const errorCode = error.code;
              const errorMessage = error.message;
              // The email of the user's account used.
              const email = error.email;
              // The AuthCredential type that was used.
              const credential = GithubAuthProvider.credentialFromError(error);
              // ...
            });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App DevTER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
         <Image src="/devter-logo.png" alt="DevTer Logo" width={60} height={60} />
         <h1 className={styles.titleH1}>DevTer</h1>
         <h3 className={styles.titleH3}>Talk about development with developers</h3>
         {
           user === null ? (
                                <Button onClick={handleClick}>
                                    <GitHub width={24} height={24} fill={'#fff'} />
                                    <span className={styles.titleButton}>Login with GitHub</span>
                                 </Button>
                              )
                          :
                          (
                            <div>
                              <h5>{user.email}</h5>
                            </div>
                          )
         }
         
      </AppLayout>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
